window:
  decorations: full

scrolling:
  history: 2048

  multiplier: 5
  faux_multiplier: 5

  auto_scroll: false

tabspaces: 2

font:
  normal:
    family: FuraCode Nerd Font

  bold:
    family: FuraCode Nerd Font

  italic:
    family: FuraCode Nerd Font

  size: 11.0

  # Scale the font size based on the monitor's DPI. This will lead to bigger text on HiDPI
  # screens and make reading text a little easier.
  # On X11 it is possible to change the DPI for each instance of alacritty by using
  # `WINIT_HIDPI_FACTOR=1.0 alacritty` to scale the font.
  scale_with_dpi: true

custom_cursor_colors: true

draw_bold_text_with_bright_colors: true

visual_bell:
  animation: EaseOutExpo
  duration: 0

background_opacity: 0.90

mouse_bindings:
  - { mouse: Middle, action: PasteSelection }

mouse:
  double_click: { threshold: 300 }
  triple_click: { threshold: 300 }

selection:
  semantic_escape_chars: ',│`|:" ()[]{}<>-'
  save_to_clipboard: false

dynamic_title: true
hide_cursor_when_typing: true
cursor_style: Beam
unfocused_hollow_cursor: true
live_config_reload: true
